CREATE TABLE cards (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       card_number VARCHAR(255) NOT NULL UNIQUE,
                       owner VARCHAR(255) NOT NULL,
                       expiration_date DATE,
                       status VARCHAR(50) NOT NULL,
                       balance DECIMAL(19, 2) NOT NULL
);
